import uuid
from datetime import datetime
from typing import Annotated, Literal

from pydantic import (
    AnyHttpUrl,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    StringConstraints,
    TypeAdapter,
    field_validator,
)

NonEmptyStr = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]
_http_url = TypeAdapter(AnyHttpUrl)


class ClientCreate(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "first_name": "John",
                    "last_name": "Doe",
                    "email": "john.doe@neviswealth.com",
                    "description": "Tech founder, interested in sustainable investing.",
                    "social_links": ["https://www.linkedin.com/in/johndoe"],
                }
            ]
        }
    )

    first_name: Annotated[NonEmptyStr, StringConstraints(max_length=200)]
    last_name: Annotated[NonEmptyStr, StringConstraints(max_length=200)]
    email: EmailStr
    description: (
        Annotated[str, StringConstraints(strip_whitespace=True, max_length=10_000)] | None
    ) = None
    social_links: list[Annotated[NonEmptyStr, StringConstraints(max_length=2_000)]] = Field(
        default_factory=list, max_length=50
    )

    @field_validator("social_links")
    @classmethod
    def _validate_links(cls, links: list[str]) -> list[str]:
        # Validate as http(s) URLs but keep the client's spelling (no normalization).
        for link in links:
            _http_url.validate_python(link)
        return links


class Client(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    first_name: str
    last_name: str
    email: str
    description: str | None
    social_links: list[str]
    created_at: datetime


class DocumentCreate(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "title": "Utility bill - March 2026",
                    "content": "Electricity utility bill issued to John Doe, 12 Baker Street, "
                    "London. Amount due: 84.20 GBP.",
                }
            ]
        }
    )

    title: Annotated[NonEmptyStr, StringConstraints(max_length=500)]
    content: Annotated[NonEmptyStr, StringConstraints(max_length=500_000)]


class Document(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    client_id: uuid.UUID
    title: str
    content: str
    created_at: datetime


class DocumentSummary(BaseModel):
    document_id: uuid.UUID
    summary: str
    method: Literal["llm", "extractive"] = Field(
        description="`llm` when generated by the configured LLM, `extractive` when built from the "
        "document's most representative sentences (no LLM configured or LLM unavailable)."
    )


ClientMatch = Literal["name", "email", "description"]
DocumentMatch = Literal["keyword", "semantic"]


class ClientSearchResult(BaseModel):
    type: Literal["client"] = "client"
    score: float = Field(ge=0, le=1)
    matched_by: list[ClientMatch]
    client: Client


class DocumentSearchResult(BaseModel):
    type: Literal["document"] = "document"
    score: float = Field(ge=0, le=1)
    matched_by: list[DocumentMatch]
    snippet: str = Field(description="The passage of the document that best matches the query.")
    document: Document


SearchResult = Annotated[ClientSearchResult | DocumentSearchResult, Field(discriminator="type")]


class ErrorResponse(BaseModel):
    detail: str
